### ISSUE TITLE
Issue with slime-repl

### ISSUE THREAD

**Issue by luismbo** [tarsius/paren-face#2]
Enabling paren-face seems to interact badly with slime-repl's slime-repl-prompt-face. When paren-face is enabled, the repl prompt gets the default face for some reason that I haven't been able to figure out.

FWIW, things work as expected when using davep's parenface.el.

Let me know if I can provide more info.

**Comment by tarsius** [comment]
It appears that `slime-repl` doesn't use `font-lock-mode` (though I don't know whether it somehow gets enabled anyway) but instead uses `slime-propertize-region` to do something similar to what that mode would do.

If you want to dim parenthesis in `slime-repl` buffers, then you have to adjust that library. I am closing  this issue because `paren-face-mode` no longer gets enabled in such buffers.
